/* 
 * 3dyne Legacy Tools GPL Source Code
 * 
 * Copyright (C) 1996-2012 Matthias C. Berger & Simon Berger.
 * 
 * This file is part of the 3dyne Legacy Tools GPL Source Code ("3dyne Legacy
 * Tools Source Code").
 *   
 * 3dyne Legacy Tools Source Code is free software: you can redistribute it
 * and/or modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 * 
 * 3dyne Legacy Tools Source Code is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
 * Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * 3dyne Legacy Tools Source Code.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * In addition, the 3dyne Legacy Tools Source Code is also subject to certain
 * additional terms. You should have received a copy of these additional terms
 * immediately following the terms and conditions of the GNU General Public
 * License which accompanied the 3dyne Legacy Tools Source Code.
 * 
 * Contributors:
 *     Matthias C. Berger (mcb77@gmx.de) - initial API and implementation
 *     Simon Berger (simberger@gmail.com) - initial API and implementation
 */



// type_wtexture.c

#include "type_wtexture.h"

void Write_WTexture( FILE *h, wtexture_t *t )
{
	// write ident
	fprintf( h, "%s ", t->ident );
}



/*
  ====================
  Write_WTextures

  ====================
*/
void Write_WTextures( wtexture_t *base, int tnum, char *name, char *creator )
{
	FILE		*h;
	int		i;

	h = fopen( name, "w" );
	if ( !h )
		Error( "Write_WTextures: can't open file '%s'\n", name );

	fprintf( h, "# wtexture file\n" );
	fprintf( h, "# generated by %s !!! DON'T EDIT !!!\n", creator );
	fprintf( h, "# <wtexture> <textue ident>\n" );
	
	for ( i = 0; i < tnum; i++ )
	{
		fprintf( h, "%d ", i );
		Write_WTexture( h, &base[i] );
		fprintf( h, "\n" );
	}

	fprintf( h, "end\n" );

	fclose( h );	
}



/*
  ====================
  Read_WTexture

  ====================
*/
void Read_WTexture( tokenstream_t *ts, wtexture_t *t )
{
	// get ident
	GetToken( ts );
	
	strcpy( t->ident, ts->token );
}



/*
  ====================
  Read_WTextures

  ====================
*/
void Read_WTextures( char *name, wtexture_t *base, int maxnum )
{
	tokenstream_t		*ts;
	int			i;

	ts = BeginTokenStream( name );
	if ( !ts )
		Error( "Read_WTextures: can't open file '%s'\n", name );

	for ( i = 0; i < maxnum; i++ )
	{
		// get texture num
		GetToken( ts );
		if ( atoi( ts->token ) != i )
			Error( "Read_WTextures: textures not sorted.\n" );

		Read_WTexture( ts, &base[i] );
	}

	if ( i == maxnum )
		Error( "Read_WTextures: reached maxnum (%d) textures.\n" );

	EndTokenStream( ts );
}
