/* 
 * 3dyne Legacy Tools GPL Source Code
 * 
 * Copyright (C) 1996-2012 Matthias C. Berger & Simon Berger.
 * 
 * This file is part of the 3dyne Legacy Tools GPL Source Code ("3dyne Legacy
 * Tools Source Code").
 *   
 * 3dyne Legacy Tools Source Code is free software: you can redistribute it
 * and/or modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 * 
 * 3dyne Legacy Tools Source Code is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
 * Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * 3dyne Legacy Tools Source Code.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * In addition, the 3dyne Legacy Tools Source Code is also subject to certain
 * additional terms. You should have received a copy of these additional terms
 * immediately following the terms and conditions of the GNU General Public
 * License which accompanied the 3dyne Legacy Tools Source Code.
 * 
 * Contributors:
 *     Matthias C. Berger (mcb77@gmx.de) - initial API and implementation
 *     Simon Berger (simberger@gmail.com) - initial API and implementation
 */



// type_plane.c

#include "type_plane.h"



/*
  ====================
  Write_Plane

  ====================
*/
void Write_Plane( FILE *h, plane_t *pl )
{
	// write plane norm
	Write_Vec3d( h, pl->norm );

	// write plane dist
	Write_fp( h, pl->dist );

	// write plane type
	fprintf( h, "%u ", pl->type );	
}



/*
  ====================
  Write_Planes

  writes an array of planes
  ====================
*/
void Write_Planes( plane_t *base, int planenum, char *name, char *creator )
{
	FILE		*h;
	int		i;

	h = fopen( name, "w" );
	if ( !h )
		Error( "Write_Planes: can't open file '%s'\n", name );

	fprintf( h, "# plane file\n" );
	fprintf( h, "# generated by %s !!! DON'T EDIT !!!\n", creator );
	fprintf( h, "# <plane num> <norm> <dist> <type>\n" );

	for ( i = 0; i < planenum; i++ )
	{
		fprintf( h, "%d ", i );
		Write_Plane( h, &base[i] );
		fprintf( h, "\n" );
	}

	fprintf( h, "end\n" );

	fclose( h );
}
	


/*
  ====================
  Read_Plane

  reads plane data into a already
  allocated pl
  ====================
*/
void Read_Plane( tokenstream_t *ts, plane_t *pl )
{
	Read_Vec3d( ts, pl->norm );

	// get dist
	GetToken( ts );
	pl->dist = atof( ts->token );

	// get type
	GetToken( ts );
	pl->type = atoi( ts->token );
}



/*
  ====================
  Read_Planes

  ====================
*/
void Read_Planes( char *name, plane_t *base, int *maxnum )
{
	tokenstream_t		*ts;
	int		i;

	ts = BeginTokenStream( name );
	if ( !ts )
		Error( "Read_Planes: can't open file '%s'\n", name );

	for ( i = 0; i < *maxnum; i++ )
	{
		// get plane number
		GetToken( ts );
		
		if ( !strcmp( "end", ts->token ) )
			break;
		
		if ( atoi( ts->token ) != i )
			Error( "Read_Planes: planes not sorted.\n" );

		Read_Plane( ts, &base[i] );
	}

	if ( i == *maxnum )
		Error( "Read_Planes: reached maxnum (%d) planes.\n", *maxnum );

	EndTokenStream( ts );

	*maxnum = i;
}
